/**
 * Test suite: Healthcare Management Service (US-2117 + US-2118)
 *
 * Behaviors tested:
 * - validateLicenseNumber: 9-11 digits required (RPPS / ADELI).
 * - create: freelance type requires licenseNumber, others don't.
 * - update: switching to freelance enforces licenseNumber.
 * - list: paginates and filters by type.
 *
 * Risks mitigated:
 * - Freelance practitioner created without RPPS — regulatory non-compliance.
 * - Type switching that bypasses license validation.
 */
import { describe, it, expect, vi, beforeEach } from "vitest"
import { prismaMock } from "../helpers/prisma-mock"

vi.mock("@/lib/logger", () => ({
  logger: { error: vi.fn(), warn: vi.fn(), info: vi.fn(), debug: vi.fn() },
}))

import {
  healthcareManagementService,
  validateLicenseNumber,
  validateOpeningHours,
} from "@/lib/services/healthcare-management.service"

beforeEach(() => {
  vi.clearAllMocks()
  prismaMock.auditLog.create.mockResolvedValue({} as never)
})

// Luhn-valid fixtures used across test cases. Generated by hand:
// 9 digits → "123456782" (Luhn sum = 40)
// 11 digits → "12345678903" (Luhn sum = 50)
const VALID_ADELI = "123456782"
const VALID_RPPS = "12345678903"

describe("validateLicenseNumber", () => {
  it("accepts 9-digit ADELI with valid Luhn", () => {
    expect(validateLicenseNumber(VALID_ADELI)).toBeNull()
  })

  it("accepts 11-digit RPPS with valid Luhn", () => {
    expect(validateLicenseNumber(VALID_RPPS)).toBeNull()
  })

  it("rejects 9-digit ADELI with invalid Luhn checksum", () => {
    expect(validateLicenseNumber("123456789")).toBe("adeli_checksum_invalid")
  })

  it("rejects 11-digit RPPS with invalid Luhn checksum", () => {
    expect(validateLicenseNumber("12345678901")).toBe("rpps_checksum_invalid")
  })

  it("rejects too short", () => {
    expect(validateLicenseNumber("12345")).toBe("license_number_invalid_format")
  })

  it("rejects too long", () => {
    expect(validateLicenseNumber("123456789012345")).toBe("license_number_invalid_format")
  })

  it("rejects 10-digit (no registry uses this length)", () => {
    expect(validateLicenseNumber("1234567890")).toBe("license_number_invalid_format")
  })

  it("rejects non-numeric", () => {
    expect(validateLicenseNumber("ABC123456")).toBe("license_number_invalid_format")
  })

  it("trims whitespace before validating", () => {
    expect(validateLicenseNumber(`  ${VALID_ADELI}  `)).toBeNull()
  })
})

describe("healthcareManagementService.create", () => {
  it("requires licenseNumber on freelance type", async () => {
    await expect(
      healthcareManagementService.create(
        { name: "Dr X", type: "freelance" },
        99,
      ),
    ).rejects.toThrow("license_number_required_for_freelance")
  })

  it("rejects invalid licenseNumber on freelance", async () => {
    await expect(
      healthcareManagementService.create(
        { name: "Dr X", type: "freelance", licenseNumber: "abc" },
        99,
      ),
    ).rejects.toThrow("license_number_invalid_format")
  })

  it("creates freelance with valid RPPS", async () => {
    const mockTx = {
      healthcareService: {
        create: vi.fn().mockResolvedValue({
          id: 1, name: "Dr X", type: "freelance", licenseNumber: VALID_RPPS,
        }),
      },
      auditLog: { create: vi.fn().mockResolvedValue({}) },
    }
    prismaMock.$transaction.mockImplementation((async (cb: any) => cb(mockTx)) as never)
    const result = await healthcareManagementService.create(
      { name: "Dr X", type: "freelance", licenseNumber: VALID_RPPS },
      99,
    )
    expect(result.type).toBe("freelance")
  })

  it("creates clinic without licenseNumber", async () => {
    const mockTx = {
      healthcareService: {
        create: vi.fn().mockResolvedValue({ id: 1, name: "CHU Test", type: "clinic" }),
      },
      auditLog: { create: vi.fn().mockResolvedValue({}) },
    }
    prismaMock.$transaction.mockImplementation((async (cb: any) => cb(mockTx)) as never)
    const result = await healthcareManagementService.create(
      { name: "CHU Test", type: "clinic" },
      99,
    )
    expect(result.type).toBe("clinic")
  })
})

describe("healthcareManagementService.update", () => {
  it("blocks switching to freelance without licenseNumber", async () => {
    const mockTx = {
      healthcareService: {
        findUnique: vi.fn().mockResolvedValue({
          id: 1, name: "X", type: "clinic", licenseNumber: null,
        }),
        update: vi.fn(),
      },
      auditLog: { create: vi.fn() },
    }
    prismaMock.$transaction.mockImplementation((async (cb: any) => cb(mockTx)) as never)
    await expect(
      healthcareManagementService.update(1, { type: "freelance" }, 99),
    ).rejects.toThrow("license_number_required_for_freelance")
  })

  it("allows switching to freelance when licenseNumber is provided", async () => {
    const mockTx = {
      healthcareService: {
        findUnique: vi.fn().mockResolvedValue({
          id: 1, name: "X", type: "clinic", licenseNumber: null,
        }),
        update: vi.fn().mockResolvedValue({
          id: 1, name: "X", type: "freelance", licenseNumber: VALID_RPPS,
        }),
      },
      auditLog: { create: vi.fn().mockResolvedValue({}) },
    }
    prismaMock.$transaction.mockImplementation((async (cb: any) => cb(mockTx)) as never)
    const r = await healthcareManagementService.update(
      1,
      { type: "freelance", licenseNumber: VALID_RPPS },
      99,
    )
    expect(r.type).toBe("freelance")
  })

  it("rejects unknown service", async () => {
    const mockTx = {
      healthcareService: {
        findUnique: vi.fn().mockResolvedValue(null),
        update: vi.fn(),
      },
      auditLog: { create: vi.fn() },
    }
    prismaMock.$transaction.mockImplementation((async (cb: any) => cb(mockTx)) as never)
    await expect(
      healthcareManagementService.update(999, { name: "X" }, 99),
    ).rejects.toThrow("service_not_found")
  })
})

/**
 * US-2117 — `validateOpeningHours` — règles métier :
 *  - format HH:MM strict
 *  - close > open par plage
 *  - pas de chevauchement entre plages d'un même jour
 */
describe("validateOpeningHours", () => {
  it("accepts a valid weekly schedule with lunch break", () => {
    const ok = validateOpeningHours({
      mon: [["09:00", "12:00"], ["14:00", "18:00"]],
      tue: [["09:00", "18:00"]],
      sun: [], // closed Sunday
    })
    expect(ok).toBeNull()
  })

  it("rejects malformed time string", () => {
    const r = validateOpeningHours({ mon: [["9:00", "12:00"]] })
    expect(r).toBe("opening_hours_invalid_time_format")
  })

  it("rejects 24:00 (out of HH:MM range)", () => {
    const r = validateOpeningHours({ mon: [["09:00", "24:00"]] })
    expect(r).toBe("opening_hours_invalid_time_format")
  })

  it("rejects close time <= open time", () => {
    const r = validateOpeningHours({ mon: [["18:00", "09:00"]] })
    expect(r).toBe("opening_hours_close_before_open")
  })

  it("rejects equal open/close (zero-length range)", () => {
    const r = validateOpeningHours({ mon: [["09:00", "09:00"]] })
    expect(r).toBe("opening_hours_close_before_open")
  })

  it("rejects overlapping ranges within same day", () => {
    const r = validateOpeningHours({
      mon: [["09:00", "13:00"], ["12:00", "18:00"]],
    })
    expect(r).toBe("opening_hours_ranges_overlap")
  })

  it("accepts adjacent (non-overlapping) ranges", () => {
    const r = validateOpeningHours({
      mon: [["09:00", "12:00"], ["12:00", "18:00"]],
    })
    expect(r).toBeNull()
  })
})
